name: Backend CI

on:
	push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
      - '!backend/README.md'

jobs:
	test:
		runs-on: ubuntu-latest
		defaults:
			run:
				shell: bash

		steps:
			- name: Checkout
				uses: actions/checkout@v4

			- name: Set up Python 3.13
				uses: actions/setup-python@v5
				with:
					python-version: '3.13'

			- name: Cache pip
				uses: actions/cache@v4
				with:
					path: ~/.cache/pip
					key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
					restore-keys: |
						${{ runner.os }}-pip-

			- name: Install dependencies
				working-directory: backend
				run: |
					python -m pip install --upgrade pip
					pip install -r requirements.txt

					- name: Lint (ruff)
						working-directory: backend
						run: |
							ruff --version
							ruff check ..

			- name: Run tests
				working-directory: backend
				run: pytest -q
